### ISSUE TITLE
Dynamic object in SSC

### ISSUE THREAD

**Issue by MUXIANGRU** [cv-rits/MonoScene#27]
Thank you for your impressive work. 
I'm a little confused about the dynamic object in SSC.When using the semantic-kitti dataset, I found the dynamic object(such as vehicles) will leave long trace in  GT voxels.
After i trained the model by the semantic-kitti dataset, I also found this question.
I wonder  how do you deal with moving objects? In the demo you show the moving objects don't leave a long trace.

I am looking forward to your reply.
Best,

**Comment by anhquancao** [comment]
Hi @MUXIANGRU, thank you!
We didn't deal with moving objects in our work. I guess the reasons are:
1. The trace is rare: it most happens if the other cars move at the speed close the vehicle speed in the same direction.
2. The shape of trace is irregular and there is little signal to predict it from a single image

**Comment by rdecharette** [comment]
Hi @MUXIANGRU,
I'm jumping in to complete Quan's message. It's indeed confusing. The SemKITTI GT comes from accumulation of Lidar scans -- thus producing these moving object traces. This makes the SSC task somehow ill-posed since perfects score implies estimating objects motion. We studied the SSC task in-depth in our survey https://arxiv.org/pdf/2011.09141.pdf (see Sec. 3.1 and 8) and an other team studied the effect of these "traces" (see https://arxiv.org/pdf/2011.09141.pdf Sec. 4.2).

As for why MonoScene does not approximate the trace, an additional reason is that in SemKITTI there are more "parked cars" than "moving cars". The easiest minimum is thus to avoid estimating any traces.
Hope that helps, good luck.
