### ISSUE TITLE
Question about Table 2.

### ISSUE THREAD

**Issue by yuxumin** [cv-rits/MonoScene#5]
Hi, thank you first for your great work MonoScene! 

I have a question about the Table 2 in paper. I an confused about the performance of 2.5D/3D method.
![Z JNS)CI~ZV4QKZ6C5)JG%V](https://user-images.githubusercontent.com/29698233/147276685-54c9e700-d9fc-4a06-891b-2a070763c841.png)
I check the paper of AICNet and 3DSketch, which report  59.2/ 33.3  and 71.3/41.1 on NYU v2 for IoU and mIoU. 
Could you please elaborate how you get the performance of AICNet and 3DSketch in Table 2?

Thank you so much

**Comment by anhquancao** [comment]
Hello @yuxumin,

Thank you for your interest in your paper!

As we mentioned in paragraph **Metrics**, Sec. 4 in our paper:
- The training and evaluation are different for indoor and outdoor methods
- Indoor methods are trained and evaluated only on occluded and surface voxels 
- Outdoor methods are trained and evaluated on all voxels (the whole scene).
- The reason is due to the sparsity of depth (indoor) vs lidar point cloud (outdoor)
-> Therefore, we retrained and evaluated all methods on all voxels.

For more in depth understanding, you can take a look at Fig. 2 and the last paragraph of Sec. 4.5.1 in the SSC survey https://arxiv.org/pdf/2103.07466.pdf

**Comment by yuxumin** [comment]
Thank you so much for the clarification!
